### ISSUE TITLE
PostCSS @apply (for tailwindCSS classes) doesn't work

### ISSUE THREAD

**Issue by johtso** [zenclabs/reactpreview#10]
I'm guessing postCSS isn't being run. Is there a chance support for this could be added? Or are there any workarounds?

**Comment by fwouts** [comment]
Thanks for the bug report! It should be possible, there are definitely a few projects that would benefit from this. I'll post an update here in the next few days :)

**Comment by fwouts** [comment]
Good news @johtso, I got it working locally.

It will likely require you to have a `postcss.config.js` file, and won't work with [Craco](https://tailwindcss.com/docs/guides/create-react-app).

Do you have a `postcss.config.js` file already, or would that be a dealbreaker?

**Comment by johtso** [comment]
@fwouts oh cool! I don't currently have a postcss config file, but I think it should be straightforward to point craco at one.

**Comment by fwouts** [comment]
Actually, I could try to infer a virtual postcss config from the Craco config. Would you be able to copy-paste the contents of your craco config (in particular the `style` section) so I can confirm whether it's doable or not?

**Comment by johtso** [comment]
Currently just super basic:

```
module.exports = {
  style: {
    postcss: {
      plugins: [
        require('tailwindcss'),
        require('autoprefixer'),
      ],
    },
  },
}
If you’re planning
```

**Comment by sevenfields-matt** [comment]
I have a similar issue using vite as our build.  It doesn't pick up any style.

**Comment by fwouts** [comment]
@sevenfields-matt Is your style injected from an `index.css` by any chance? You may need to set up a `Wrapper.tsx` component that imports it, more instructions at https://reactpreview.com/usage. If it's a PostCSS issue, just hang on for a few hours :)

**Comment by sevenfields-matt** [comment]
@fwouts Yes that was it.

`
import React from "react";
import "../src/index.css";

interface Props {
	children: React.ReactNode
}

export const Wrapper: React.FC<Props> = ({ children }: Props) => (
	<>
		{children}
	</>
);
`

**Comment by fwouts** [comment]
@johtso After investigation, it wasn't possible to create a virtual postcss config file, so you'll need to create one in your project 😞

I've just published v0.2.2 which should solve this. Let me know how you go!

**Comment by johtso** [comment]
That's working great! 🎉

**Comment by fwouts** [comment]
Woo-hoo! And thanks for filing more issues, will try to get all that solved in the next week or so 😁
