### ISSUE TITLE
"React Preview" Output had to be opened before I saw the "View in React Preview"

### ISSUE THREAD

**Issue by sevenfields-matt** [zenclabs/reactpreview#11]
I didn't see the feature until I selected React Preview output pane.  Then it said "Bootstrapped sucessfully" and then I could preview

**Comment by fwouts** [comment]
Thanks for the bug report! What platform are you on?

**Comment by sevenfields-matt** [comment]
Windows.  

It sort of appeared like the "React Preview needs to download packages" didn't really work correctly.

I uninstalled and reinstalled and it didn't solve the issue..  As soon as I selected the output pane worked great and continues to do so.

**Comment by utrolig** [comment]
Confirmed, same happened to me on Mac OSX

**Comment by ahmetskilinc** [comment]
Where do you see the "React Preview output pane"

**Comment by sevenfields-matt** [comment]
![image](https://user-images.githubusercontent.com/48861400/123457748-1725d500-d599-11eb-8465-ef9269e659a5.png)

**Comment by ahmetskilinc** [comment]
I don't even have that. Do I need to add it there or anything?

**Comment by sevenfields-matt** [comment]
@ahmetskilinc No it just appeared once I installed the extension.  Maybe you have a separate issue.

**Comment by fwouts** [comment]
Hi all, there was indeed a race condition that could lead to the preview CodeLens not showing up after a fresh install. It should now be fixed in v0.2.3, which was just released. Closing this for now, but feel free to reopen if you experience this again!
