### ISSUE TITLE
Can you customize the server/webpack config?

### ISSUE THREAD

**Issue by tomparkp** [zenclabs/reactpreview#12]
I have a React Native project where I use Expo to render web versions of the components. It would be great to use this extension but the expo webpack config is pretty complex so it would be great to be able to supply a custom webpack config for cases like this.

**Comment by fwouts** [comment]
Hi @tomparkp, unfortunately React Preview doesn't use webpack at all. It's built upon [Vite](http://vitejs.dev).

If you have a public project similar to yours that you could point to for future exploration of this kind of feature, I'd appreciate that!

**Comment by tomparkp** [comment]
I think for supporting more advanced setups/use cases the answer probably lies in allowing consumers to specify their own `vite.config.js` - is that what `reactpreview.config.js` is doing or is it limited to only the `alias` and `publicDir` fields? With the ability to override the Vite config it would make it possible to integrate things like Expo/React Native via https://github.com/necolas/react-native-web

**Comment by fwouts** [comment]
At this stage you can't customise `vite.config.js` aside from `alias` and `publicDir`. Under the hood React Preview uses several custom Vite plugins (e.g. a virtual filesystem plugin to support preview-as-you-type), so it wouldn't be easy to make merge it with a user-provided config.

I just tried to get react-native-web examples to work with it, and it looks like there is another hurdle anyway: react-native is written in Flow, which isn't supported by esbuild (dependency of Vite).

If you find me an example of a react-native-web app working with Vite, I'll be happy to give it another try!

**Comment by tomparkp** [comment]
I was actually able to get it working with simple alias from `react-native` to `react-native-web`. There are other hurdles though, specifically how to deal with things like image imports.

**Comment by tomparkp** [comment]
I'm not sure if react native being written in flow is an issue as you alias to `react-native-web` so everything actually gets imported from that package instead of react native.

**Comment by fwouts** [comment]
That's a good point, I didn't realise it was meant to replace it entirely with an alias. Definitely something to explore more!

**Comment by fwouts** [comment]
Hey @tomparkp, in v0.4.2 published today, you can now specify a custom Vite config in `reactpreview.config.js`:
```
module.exports = {
  vite: {
    ...  // your vite config, which will be merged with React Preview's
  },
};
```

Let me know if you give it a try :)
