### ISSUE TITLE
Add a key command for "Show React Preview for current component"

### ISSUE THREAD

**Issue by sevenfields-matt** [zenclabs/reactpreview#13]
I may not always have the preview open for the component I'm working on. 

I think it makes sense to have a key command available that opens the preview for the current component that you are editing the body of. That way I can be editing a component and not have to grab the mouse to preview it.

**Comment by fwouts** [comment]
Nice idea! Do you have a specific key command in mind? I'm thinking perhaps the same command used for Markdown preview?

**Comment by sevenfields-matt** [comment]
Forgive me if I'm wrong.  But I think you can add a command to VS Code that would show up in the command palette.  Then I believe if its in the command palette then I would be free to bind it to whatever key I want.

As a default the markdown preview is probably fine.  But I think its reasonable to not even have a default and just let the user decide.

I'm going to acknowledge that I have never built an addin for vs code.  But its probably this page that would help with what I'm talking about:
[](https://code.visualstudio.com/api/extension-guides/command#creating-new-commands )

**Comment by fwouts** [comment]
No, you're spot on :)

**Comment by fwouts** [comment]
Hey @sevenfields-matt, sorry this took a while but it's now implemented in v0.4.2 😄 

Try Cmd/Ctrl+K V to open React Preview!

Feel free to reopen if you run into any issues.

**Comment by sevenfields-matt** [comment]
Works great!

**One issue some people might face:**
If you have the VIM plugin ctrl-k is a bound key, so for me it didn't work initially with the default keybinding.  I rebound the key and everything works great. The command works from the command palette out of the box with VIM plugin.

Thanks for the feature.

**Comment by fwouts** [comment]
Nice, and thanks for calling that out, I wouldn't have realised. I'm sure VIM users are tech literate enough to know how to rebind keys anyway 😂
