### ISSUE TITLE
Aliased imports by use of `baseUrl` are not resolved

### ISSUE THREAD

**Issue by utrolig** [zenclabs/reactpreview#18]
Example:
`tsconfig.json` has `"baseUrl": "src"`

```tsx
import logger from 'utils/logger';
```

should resolve to `./src/utils/logger`

**Comment by fwouts** [comment]
Hey @utrolig, this should now be fixed in v0.2.3 thanks to https://github.com/aleclarson/vite-tsconfig-paths :)

Feel free to reopen if you experience any issues.
