### ISSUE TITLE
CSS compilation errors are overly intrusive and don't disappear when fixed

### ISSUE THREAD

**Issue by johtso** [zenclabs/reactpreview#20]
Currently as you're typing something new into your CSS, while the code is invalid a big red error banner appears at the top of the page. This banner then doesn't seem to disappear when the code becomes valid.

I don't think it really makes sense to have such an intrusive indication that your code is invalid when you're in the middle of typing something out. If it was more subtle, and didn't change the position of the page (maybe living in the console area) that would be one thing, but the way it is currently, it gets in the way of seeing how your CSS updates might have subtly changed the way your page is rendered.

The fact that it doesn't disappear once compilation is successful just seems like a bug.

**Comment by fwouts** [comment]
The error not disappearing on success is definitely a bug!

In terms of error-as-you-type experience, what do you think would be good? Perhaps delay showing any error by a few seconds after you stop typing?

**Comment by johtso** [comment]
> The error not disappearing on success is definitely a bug!
> 
> In terms of error-as-you-type experience, what do you think would be good? Perhaps delay showing any error by a few seconds after you stop typing?

debouncing is an option.. but that would have a negative impact on how responsive things are. It's nice to be able to comment/uncomment a line and instantly see what the difference looks like.

Maybe having it in the console area at the bottom would make the most sense? Hard to say..

**Comment by fwouts** [comment]
@johtso That's mostly in line with what I had in mind. What do you think of this?

https://user-images.githubusercontent.com/772570/123704050-945a8e00-d8a8-11eb-95ff-e1b9b67e5c9b.mov

**Comment by johtso** [comment]
That looks great! I was going to suggest something along those lines as well! A smaller indicator that can be clicked on to see the full error, and making it absolutely positioned so it doesn't change the layout of the page. Perfect!

**Comment by fwouts** [comment]
Wonderful. You should see an update pop up in a few minutes once Visual Studio Marketplace has processed it :)

**Comment by johtso** [comment]
Oh nice, you even added a delayed automatic revealing of the full error message. Slick!
