### ISSUE TITLE
style.module.scss is not loading

### ISSUE THREAD

**Issue by sameroso** [zenclabs/reactpreview#25]
![image](https://user-images.githubusercontent.com/53017109/123440388-1bf28500-d5a9-11eb-9d93-280b31d48853.png)

Trying to load component that uses style.module.scss and shows this error

**Comment by fwouts** [comment]
Thank you for the bug report @sameroso. Do you have the Sass package installed already in that repo?

**Comment by anurag145** [comment]
I installed Sass package and it worked, but I already have node-sass installed for the same project? Ideally that should have worked right? or for now do we need to add sass package as a dev dependency?

**Comment by fwouts** [comment]
Hi all, thanks for the bug report!

You currently do need to install `sass` in your project for React Preview to work. This is due to how Vite (the engine behind React Preview) works under the hood.

I've opened a PR in Vite, depending on how that go we may be able to fix it :)

**Comment by fwouts** [comment]
Hi there, you won't need `sass` installed in your project from React Preview v0.3.0 onwards. It should be available in a few minutes once it's gone through Microsoft's moderation pipeline :)

Please feel free to reopen this if you still see issues.
