### ISSUE TITLE
The bug bash

### ISSUE THREAD

**Issue by Milo123459** [zenclabs/reactpreview#30]
A series of bugs, errors and features that need to be implemented all written in one issue.

# ~~Bug 1: CSS doesn't load~~

~~CSS isn't loading for my `Home` component defined [here](https://github.com/Milo123459/website/blob/edcbc9ab29a2d7ca9376d21c4631e919469028d3/src/pages/index.tsx#L5)~~

Was just missing configuration, create a `__reactpreview__/Wrapper.tsx`, add the following code:
```ts
import React from 'react';
import '../src/styles/globals.css';

export const Wrapper = React.Fragment;
```

# Bug 2: Routing doesn't work

https://user-images.githubusercontent.com/50248166/123679587-8fadbf80-d83f-11eb-92cc-332325dbd982.mp4

# Bug 3: Next support is lacking

Support for NextJS is a bit lacking. Would be better if there was a way to preview a whole Next app.

# ~~Bug 4: Open Preview text doesn't move with code moving~~

~~The text saying `Open Home in React Preview` doesn't move when I move the code.~~

**Comment by fwouts** [comment]
Hey @Milo123459, thank you!

Bug #1 is just a missing configuration :) Check out https://reactpreview.com/usage for more details.

Here's the __reactpreview__/Wrapper.tsx you need:
```ts
import React from 'react';
import '../src/styles/globals.css';

export const Wrapper = React.Fragment;
```

Routing support is unlikely to be something React Preview would support natively, but it may be something you can also support via a Wrapper. Improved Next support is coming though!

Regarding the magnifying glass, it's not something I've seen before. Are you sure it's not coming from another extension?

**Comment by Milo123459** [comment]
1) Thank you for clearing up bug number 1! 
2) Let me see.

**Comment by Milo123459** [comment]
2 Was actually caused by the MDX extension I installed earlier. My bad!

**Comment by fwouts** [comment]
Hi @Milo123459, bug #4 is now fixed in v0.3.0, which should appear in the VS Code Marketplace shortly :)

NextJS support is something I'm tracking already. Let me know if you're OK to close this issue after you try it out!

**Comment by Milo123459** [comment]
Fantastic!

**Comment by fwouts** [comment]
Hey @Milo123459, sorry it's been a while without much updates!

I think routing isn't something that React Preview will be able to support natively, but the next release will intercept redirects so you won't be sent to the browser with a broken URL :)

See video below:

https://user-images.githubusercontent.com/772570/134465799-d957b4bf-92fb-4757-8c7f-8b8999a1589a.mov

I'm going to close this bug, but feel free to open new ones if you encounter new issues.
