### ISSUE TITLE
Other options to open a preview tab

### ISSUE THREAD

**Issue by Phyya** [zenclabs/reactpreview#32]
I'm hovering over a react component and there is no link pop-up to open preview. Help

**Comment by fwouts** [comment]
Hi @Phyya, what is the file name? React Preview can only work with **.jsx** or **.tsx** files. You should see the link appear over the component automatically, no need for hovering.

It's also possible that you're experiencing the same bug as https://github.com/zenclabs/reactpreview/issues/26

**Comment by fwouts** [comment]
Hi @Phyya, you will now see a button in the top-right corner to open React Preview. Let me know how you go!

<img width="1136" alt="Screen Shot 2021-08-02 at 3 38 25 pm" src="https://user-images.githubusercontent.com/772570/128125873-38bf7b12-e547-4fed-be34-e13d32dd4355.png">

**Comment by Phyya** [comment]
Thank you. It works perfectly now. Great job
