### ISSUE TITLE
Rename project to Component Preview

### ISSUE THREAD

**Issue by arvigeus** [zenclabs/reactpreview#36]
If you think adding support for different components other than React would be feasible in the future, a more generic name would be more suitable.

**Comment by fwouts** [comment]
Hey @arvigeus, thanks for the suggestion.

While it would technically be feasible to support other frameworks, it would also introduce an amount of complexity that I'm unable to manage as a one-man team. I do hope to get there ultimately, but realistically it probably won't happen for another year at least!

In the meantime, I prefer to keep the branding specific 🙂 

In the meantime, if you're interested in other projects that work with other stacks than React, I'd invite you to check out https://github.com/zenclabs/viteshot. This is based on the same principles as React Preview, but doesn't have the same inherent complexities (e.g. no need for prop types analysis, callback interception or user-friendly error handling).

Thanks for bringing this up!
