### ISSUE TITLE
Ability to disable open buttons above component name 

### ISSUE THREAD

**Issue by nucleartux** [zenclabs/reactpreview#37]
**Is your feature request related to a problem? Please describe.**
I have large project and when I'm trying to select some lines of code height of viewport changes due to rendering of "Open Component in React Preview", very frustrating to me.

**Describe the solution you'd like**
Ability to disable such behaviour and open preview from command palette or from other places, not sure about that, but for example from left side, around line numbers maybe.

**Comment by fwouts** [comment]
Hey @nucleartux, thanks for the feedback. You have a good point! I'm planning to implement what you've mentioned in the next few weeks.

In the meantime, do you think it would help to simply remove preview capability for non-exported components? I've been wondering how useful that is.

**Comment by nucleartux** [comment]
Vice versa for me, most of the time I'm viewing non-exported components, because in my projects such components are dumb (view) components and exported are smart (containers, with logic) components.

**Comment by fwouts** [comment]
Glad I asked. I'll push this up the priority list 🙂

**Comment by fwouts** [comment]
Hey @nucleartux, I'm planning to add a button (see top right in first screenshot) which is a shortcut for a command (which can also be bound to a keyboard shortcut). CodeLens will still be shown by default, but you can disable them in settings.

Thoughts?

<img width="1136" alt="Screen Shot 2021-08-02 at 3 38 25 pm" src="https://user-images.githubusercontent.com/772570/127809676-ba0fc48e-db77-4a36-b664-f01d0b92ff85.png">
<img width="1136" alt="Screen Shot 2021-08-02 at 3 38 33 pm" src="https://user-images.githubusercontent.com/772570/127809694-c57af501-63fb-477f-b3d3-cb01e6d021bd.png">
<img width="1136" alt="Screen Shot 2021-08-02 at 3 39 18 pm" src="https://user-images.githubusercontent.com/772570/127809703-dd67d1bc-d38d-4f60-b6fc-a6eb61fae005.png">

**Comment by nucleartux** [comment]
Looks great!

**Comment by fwouts** [comment]
Hey @nucleartux, this is now live in v0.4.2. Would you be able to give it a try and let me know how you go?

**Comment by nucleartux** [comment]
Works fine now, thanks! ❤️
