### ISSUE TITLE
Allow CSS preprocessor configuration

### ISSUE THREAD

**Issue by cyco130** [zenclabs/reactpreview#38]
We use [Ant](https://ant.design/) in one of our projects and we load their uncompiled .less styles instead of .css in order to do some customizations. Unfortunately Ant uses inline JavaScript in their .less files which has to be explicitly enabled. But ReactPreview doesn't allow this because the related Vite config options aren't available at this time.

From what I see in the other issues, I understand a fully custom Vite config is not doable at the moment. But allowing the customization of Vite's CSS preprocessor configurations would solve the problem and allow the use of Ant, “the second most popular React component library”.

**Comment by fwouts** [comment]
Hey @cyco130, thanks for sharing this. Would you be able to share an example Vite config needed for Ant to work?

**Comment by cyco130** [comment]
Sure, this is what I normally do:

```js
const viteConfig = {
	css: {
		preprocessorOptions: {
			less: {
				javascriptEnabled: true
			}
		}
	}
}
```

**Comment by fwouts** [comment]
Perfect, thanks. Pushed up the priority list!

**Comment by fwouts** [comment]
Hi @cyco130, good news, this is now possible in v0.4.2 :)

You can add a `vite` option in `reactpreview.config.js`, like so:
```
module.exports = {
  vite: {
    css: {
      preprocessorOptions: {
        less: {
          javascriptEnabled: true,
        },
      },
    },
  },
};
```

Let me know how you go!

**Comment by cyco130** [comment]
Just tried it, works like a charm, thank you!

**Comment by fwouts** [comment]
Sweet. I have some screenshot tests set up with Ant now so this will should hopefully never break 😁
