### ISSUE TITLE
can't resolve import path with jsconfig.json path

### ISSUE THREAD

**Issue by moharifhidayat7** [zenclabs/reactpreview#44]
### Describe the bug

error when import component with jsconfig path
`Failed to resolve import "@components/Navbar" from "components/Layout.jsx". Does the file exist?`

### Reproduction

1. setup path with jsconfig.json file
`{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@components/*": ["components/*"],
      "@styles/*": ["styles/*"]
    }
  }
}
`
2. import inside component
`import Navbar from '@components/Navbar'`
3. open in ReactPreview

**Comment by fwouts** [comment]
Hi @moharifhidayat7, did you find a way around this? In case you haven't yet, you'll find some useful info in https://reactpreview.com/docs/config/aliases :)
