### ISSUE TITLE
Unique names for default generated props

### ISSUE THREAD

**Issue by ntcaston** [zenclabs/reactpreview#46]
**Is your feature request related to a problem? Please describe.**

Two problems:

1. Sometimes I have multiple prop fields that will be used as keys in child components (e.g. an `id` field). I will often get the `Each child in a list should have a unique "key" prop` error as they all end up with `id` as the key.
2. This is less of an issue, but if there are duplicated field names in different sub-objects (in my case `school.name` and `subject.name`) they both have the same generated value (`"name"`) so it's not obvious if I've put the correct one in the right place or made some copy-paste error.

**Describe the solution you'd like**

I was thinking that default-generated props could have unique names, maybe just appending + incrementing a number to the ones that are already there. Or perhaps the generated name includes the parent field name (e.g. "school.name" instead of just "name") or the name of the fn they were returned from.

**Comment by fwouts** [comment]
Thank you for the suggestion!

The solution was a one-line fix from `path[path.length - 1]` to `path.join(".")` in the function that generates string values :)

This will be live in the next release, hopefully next week.

**Comment by ntcaston** [comment]
Thanks for the quick turnaround!
