### ISSUE TITLE
CSS Not being applied

### ISSUE THREAD

**Issue by jackvdp** [zenclabs/reactpreview#67]
### Describe the bug

I'm getting this error in the preview and getting my react components with no CSS styling:

TypeError: Failed to fetch dynamically imported module: http://localhost:3140/preview/__reactpreview__/Wrapper.tsx

### Reproduction

// react-review.config.js

```
module.exports = {
  // Aliasing of paths to directories.
  //
  // Note: tsconfig.json path aliases are automatically detected, they can be omitted.
  alias: {
    // app: "src",
  },

  // Public assets directory.
  publicDir: "public",

  // SVGR configuration.
  svgr: {
    componentName: "ReactComponent",  // use "default" for default exports
  },

  // Wrapper file configuration.
  wrapper: {
    path: "__reactpreview__/Wrapper.tsx",
    componentName: "Wrapper",
  },
};

```
// Wrapper.tsx

```
import "styles.css";
import React from "react";

export const Wrapper = React.Fragment;
```

### React Preview version

v.0.7.1

### System Info

```shell
VS Code
```

### Used Package Manager

npm

**Comment by fwouts** [comment]
Hi @jackvdp, the CSS import needs to be relative to Wrapper.tsx, so it's likely something like "../src/style.css". Would you be able to try that?

**Comment by jackvdp** [comment]
Yes, you're right – the CSS file was in the public folder, and I thought I didn't need to state the full path – I'm new to React! Thank you. Great extension!

**Comment by fwouts** [comment]
Woo-hoo! 😁
