### ISSUE TITLE
The installation of the extension got blocked by BitDefender anti-virus

### ISSUE THREAD

**Issue by metawire** [zenclabs/reactpreview#69]
### Describe the bug

![image](https://user-images.githubusercontent.com/87371219/148650870-4f60efe3-4412-43b6-a9a2-a8eb668c87ec.png)

### Reproduction

1. try to install the extenstion in VS Code on Windows 10 + BitDefender Total Security

### React Preview version

v0.7.1 (Beta)

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 1.98 GB / 15.96 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Visual Studio: 17.0.31912.275 (Visual Studio Community 2022), 16.11.31911.196 (Visual Studio Community 2019)
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.55)
    Internet Explorer: 11.0.19041.1202
```

### Used Package Manager

npm

**Comment by fwouts** [comment]
Thank you for letting me know. It looks like a false positive, so I've reported the page at https://www.bitdefender.com/consumer/support/answer/29358.
